### ISSUE TITLE
Certificate symbolic link not working

### ISSUE THREAD

**Issue by sergiowalls** [Jigsaw-Code/outline-server#424]
I generated my own certificates (using Let's Encrypt) and I replaced `shadowbox-selfsigned.crt` and `shadowbox-selfsigned.key` with the new certificate and the private key. Outline server was working but, when I try to replace these files with symbolic links (to make easier certification renew) it outputs following error:

```
D2019-04-20T20:51:31.545Z 8 main.js:100] === Config ===
D2019-04-20T20:51:31.547Z 8 main.js:101] SB_PUBLIC_IP: XXXXX
D2019-04-20T20:51:31.547Z 8 main.js:102] SB_METRICS_URL: https://metrics-prod.uproxy.org
D2019-04-20T20:51:31.547Z 8 main.js:103] ==============
I2019-04-20T20:51:31.550Z 8 main.js:112] Starting...
I2019-04-20T20:51:31.556Z 8 main.js:121] Prometheus is at 127.0.0.1:9090
I2019-04-20T20:51:31.556Z 8 main.js:122] Node metrics is at localhost:9091
I2019-04-20T20:51:31.556Z 8 main.js:133] outline-ss-server metrics is at localhost:9092
E2019-04-20T20:51:31.562Z 8 main.js:182] Error: ENOENT: no such file or directory, open '/opt/outline/persisted-state/shadowbox-selfsigned.crt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /root/shadowbox/app/server/main.js:158:29
    at Generator.next (<anonymous>)
    at fulfilled (/root/shadowbox/app/server/main.js:17:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

And same error for `shadowbox-selfsigned.key`. 

My symbolic links look like:

```
ls /opt/outline/persisted-state/ -la

...
lrwxrwxrwx 2 root root   49 Apr 20 20:38 shadowbox-selfsigned.crt -> /etc/letsencrypt/live/XXXXX/cert.pem
lrwxrwxrwx 1 root root   52 Apr 20 20:38 shadowbox-selfsigned.key -> /etc/letsencrypt/live/XXXXX/privkey.pem
...
```

It seems that Docker won't work well with symbolic links outside the container (in the host).

**Comment by sergiowalls** [comment]
I fixed it with a cron that copies the new files to Outline folder.
