### ISSUE TITLE
Outline Manager

### ISSUE THREAD

**Issue by spoow83** [Jigsaw-Code/outline-server#650]
Hello,

how can i fix the below issue?

**i'm using MBP 10.12.6**

Uncaught Exception:
TypeError: Cannot read property 'Access-Control-Request-Headers' of undefined
    at Function.<anonymous> (/private/var/folders/bf/v9f2xmwj3q356n1n7jd_gh2h0000gn/T/AppTranslocation/3F1F806D-9254-47E2-A91A-0CBB53A27EEC/d/Outline Manager.app/Contents/Resources/app.asar/index.js:154:37)

**Comment by spoow83** [comment]
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createMainWindow (/Applications/Outline Manager.app/Contents/Resources/app.asar/index.js:65:17)
    at App.<anonymous> (/Applications/Outline Manager.app/Contents/Resources/app.asar/index.js:236:26)
    at App.emit (events.js:203:13)
    at App.EventEmitter.emit (domain.js:476:20)
    at App.emitter.emit (/Applications/Outline Manager.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:278:20)
    at App.topLevelDomainCallback (domain.js:131:23)

**Comment by alalamav** [comment]
Hi, the [newest release](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.5.2) should fix this problem. Please reopen this issue if this is not the case.

**Comment by spoow83** [comment]
@alalamav  Fixed thanks!
